name: JSON Schema Validation
on: [pull_request]
jobs:
  validate-json-schema:
    name: JSON Schema Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if json schema was changed
        id: check-for-changed-schemas
        uses: tj-actions/changed-files@v41
        with:
          files: |
            json-schema/*/*.json
      - name: Validate JSON Schema files
        if: steps.check-for-changed-schemas.outputs.any_changed == 'true'
        uses: cardinalby/schema-validator-action@v3
        with:
          file: "json-schema/*/*.json"
          schema: https://json-schema.org/draft/2020-12/schema
